# CIFAR-100 with 10000 labeled samples configuration
# Auto-resume: Training will automatically resume from the last checkpoint if available
# Checkpoint location: results/cifar100@10000/checkpoint.pth.tar

dataset: cifar100
num_labeled: 10000
arch: wideresnet
batch_size: 16
lr: 0.03
wdecay: 0.001
expand_labels: true
seed: 5
out: results/cifar100@10000

# Default parameters (can be overridden)
gpu_id: 0
num_workers: 4
total_steps: 1048576  # 2^20
eval_step: 1024
start_epoch: 0
warmup: 0
nesterov: true
use_ema: true
ema_decay: 0.999
mu: 7
lambda_u: 1.0
T: 1.0
threshold: 0.95
resume: ""  # Leave empty for auto-resume functionality
amp: false
opt_level: "O1"
local_rank: -1
no_progress: false 